### ISSUE TITLE
Using this tool for cocoa application

### ISSUE THREAD

**Issue by kapil0408** [imkira/mobiledevice#13]
I used this tool for command line it is working fine as described by you. thanks for this wonderful utility.

but i want to implement this in my cocoa application (Mac OS X). i downloaded your project and implemented in my mac app also add "MobileDevice Framework". it built successfully. how can i access the UDID, list_device, list_device_props. when i connect my IOS  device then i want to access connected device information in mac application.

Please see the attached file.

[MobileDeviceMacDemo.zip](https://github.com/imkira/mobiledevice/files/636183/MobileDeviceMacDemo.zip)

It would be great if any help
Thanks.

**Comment by imkira** [comment]
Well, if you want to use it as a library, you can't.
If you want to implement it like I'm doing, you will have to look at the code.
Some stuff like parsing command line options and printing out is CLI-only, so you can ignore that.

**Comment by kapil0408** [comment]
Thanks for your reply.
is there any way to implement to access file system of device in mac application.
I saw also libimobiledevice library. do you any idea to implement this library in mac application

Please see the links:
1. https://github.com/libimobiledevice
2. http://www.libimobiledevice.org

Any help will be very appreciate.

**Comment by imkira** [comment]
You should probably contact the authors of libimobiledevice but, at first glance it seems to be possible. Please take a look at
http://www.libimobiledevice.org/docs/html/afc_8h.html

**Comment by kapil0408** [comment]
Thanks for reply. i will look into it.
