### ISSUE TITLE
Seems tunnel has broken?

### ISSUE THREAD

**Issue by CodeLife2012** [imkira/mobiledevice#14]
Currently I use 2.0.0, but failed to use `mobiledevice tunnel` in two device, all log out 

> Failed to bind to port 22!

Can I enable verbose log to figure out what really happened?

**Comment by imkira** [comment]
Can you try ports equal to or above 1024?

**Comment by CodeLife2012** [comment]
I always port to 2222  or  other larger value

**Comment by CodeLife2012** [comment]
Any way to enable verbose log?
@imkira

**Comment by imkira** [comment]
What do you mean by "port to 2222" ? Your error message shows "port 22".

**Comment by CodeLife2012** [comment]
Sorry,   seems I make a mistake by bind device 2222 to local 22,  it should be `tunnel 2222 22`, I make a  wrong assume of the `from to port`. Thanks for you reply.

**Comment by imkira** [comment]
Nice! I'm closing this assuming you're already found the solution to your problem.
