### ISSUE TITLE
Can't use get_device_prop when Android device is plugging

### ISSUE THREAD

**Issue by passchaos** [imkira/mobiledevice#15]
When one Android device and one iOS device plug simultaneously, `mobiledevice get_device_prop` just output '!AMDeviceIsPaired'.

**Comment by imkira** [comment]
Have you tried listing devices first with list_devices ?

**Comment by passchaos** [comment]
Yeah, list_devices works, then I use '-u' option, but I get nothing but '!AMDeviceIsPaired'.

**Comment by imkira** [comment]
And how many devices are there listed?

**Comment by passchaos** [comment]
Just one Android device and one iOS device.
 Details:
```
mobiledevice version
=> 2.0.0
mobiledevice list_devices
=> f5e93e1226e1aab9157bac6d1377630496a394f3
mobiledevice get_device_prop -u f5e93e1226e1aab9157bac6d1377630496a394f3 ProductVersion
=> !AMDeviceIsPaired
mobiledevice get_device_prop -u f5e93e1226e1aab9157bac6d1377630496a394f3 ProductType
=> !AMDeviceIsPaired
```
After I pull up the Android device, everything become OK.

**Comment by passchaos** [comment]
My fault. I need trust the device. Very Sorry!
