### ISSUE TITLE
Installation is failing on High Sierra make fail with ld: framework not found MobileDevice

### ISSUE THREAD

**Issue by caipivara** [imkira/mobiledevice#18]
My OSX version: `10.13.4` 

# Manual try

```
git clone git://github.com/imkira/mobiledevice.git
cd mobiledevice
make
```

I got: 

> ld: framework not found MobileDevice

# Brew try

```
$ brew install mobiledevice
mobiledevice: This formula either does not compile or function as expected on macOS
versions newer than Sierra due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.
```

**Comment by thulasipavankumar** [comment]
any update on the issue ??

**Comment by loveiset** [comment]
It seems this project have not updated for a long time

**Comment by DomT4** [comment]
The project seems pretty dead but I've submitted a fix in https://github.com/imkira/mobiledevice/pull/20.

**Comment by caipivara** [comment]
Duplicate of https://github.com/imkira/mobiledevice/issues/16
