### ISSUE TITLE
Can we Connected Multiple device 

### ISSUE THREAD

**Issue by ntabhi** [imkira/mobiledevice#6]
Can we pass UUID while performing actions, so that we can access it mobiledevice on multiple devices

**Comment by RuudPuts** [comment]
This is being worked on as we speak! No eta yet, sorry.

**Comment by imkira** [comment]
@ntabhi What you want is already available in the ```multiple-devices``` branch ( https://github.com/imkira/mobiledevice/tree/feature/multiple-devices )

Me and @RuudPuts are reviewing the code and once we're finished we will merge this into the master branch.

**Comment by ntabhi** [comment]
@RuudPuts and @imkira  Thanks for the support.

**Comment by imkira** [comment]
@ntabhi I just released version 2 of mobiledevice (master branch) adding support for multiple devices.
You basically now have a ```-u <udid>``` to execute a command on a specific device.
Anyway, there are many changes to the command line, so please read the README before using.
