### ISSUE TITLE
mobiledevice only works intermittently 

### ISSUE THREAD

**Issue by kdkanda** [imkira/mobiledevice#8]
Mac mini Server (Mid 2010)
OS Version 10.10.2 (14C1510)

:local builder$ mobiledevice list_devices
:local builder$ mobiledevice list_devices
:local builder$ mobiledevice list_devices
:local builder$ mobiledevice list_devices
:local builder$ mobiledevice list_devices
791c6d8ed305849fdae50be63a6560XXXXXXXXXX
:local builder$ mobiledevice list_devices
:local builder$ mobiledevice list_devices
:local builder$ mobiledevice list_devices
:local builder$ mobiledevice list_devices
:local builder$ mobiledevice list_devices
:local builder$ mobiledevice list_devices
791c6d8ed305849fdae50be63a6560XXXXXXXXXX
:local builder$ mobiledevice list_devices
:local builder$ mobiledevice list_devices
:local builder$ mobiledevice list_devices

**Comment by imkira** [comment]
Good catch.
Can you try running that again but this time with 

```shell
mobiledevice list_devices -t 1000
```

**Comment by kdkanda** [comment]
Adding -t solved  the issue . Really appreciate your effort on this project .

**Comment by imkira** [comment]
No problem. Let me know if something else comes by. I am wondering wether the default timeout should be increased. Unfortunately the API is asynchronous and there is no "finished listing devices" event coming.
